spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      leak-detection-threshold: 30000

logging:
  level:
    com.bny.lfdapi: INFO
    org.springframework.jdbc: WARN
