spring:
  datasource:
    url: jdbc:mysql://bny-demo.c3uyq60ukgb6.us-east-2.rds.amazonaws.com:3306/bny_data_services
    username: admin
    password: password
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

logging:
  level:
    com.bny.lfdapi: DEBUG
    org.springframework.jdbc: DEBUG
