spring:
  datasource:
    url: jdbc:mysql://localhost:3306/investing_dev
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:password}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

logging:
  level:
    com.bny.lfdapi: DEBUG
    org.springframework.jdbc: DEBUG
